generatorVersion : 1.0.0
hostNamePrefix : dspacepkg
projectInfo:
  jiraURL: https://www.milieuinfo.be/jira/browse/DSPACE
  bambooURL: https://www.milieuinfo.be/bamboo/browse/ACDCOMP-DM
  confluenceURL: https://www.milieuinfo.be/confluence/display/DSPACE/home+page
  projectLead:
    name: joske
    telephoneNb: 02 123 45 67
    email: jos@mail.com
machineSpec:
  nbOfCpus: 2
  nbOfVCpus: 4
  amountOfRam: 8192
  osImage:
    image: ubuntu-16.04-2016061001
    size:  10240
    deviceType: HDD
  dataDisks:
      - sequenceNb: 1
        deviceType: HDD
        size: 512000
        fileSystemType: EXT4
        mountPoint: /opt/tomcat/data
        user: root
        group: root
        permissions: 0750
  networkSettings:
    incomingTcpPorts:
        - 8080
    sshAccessGroups:
      - cn=ontwikkelaars_acd,ou=posixsshaccess,ou=posix,ou=groups,dc=milieuinfo,dc=be
      - cn=admins_acd,ou=posixsshaccess,ou=posix,ou=groups,dc=milieuinfo,dc=be
softwareSpec:
  debianPackages:
    - name: oracle-java7
      version: LATEST
    - name: acdtomcat7
      version: LATEST
externalContext:
  registerDNS: true
  monitoringTemplates:
    - linux
    - jmx
